In [43]:
import numpy as np
from numpy.random import randn
from numpy.linalg import inv, qr

## 将数组以二进制格式保存到磁盘

In [12]:
arr = np.arange(10)
np.save('../resource/some_array.npy', arr)
res = np.load('../resource/some_array.npy')
print(res)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
# 保存多个数组到一个压缩文件
np.savez('../resource/array_archive.npz',a=arr,b=arr)
res = np.load('../resource/array_archive.npz')
print(res['b'])

[0 1 2 3 4 5 6 7 8 9]


## 存取文本文件

In [15]:
arr = np.loadtxt('../resource/array_ex.txt', delimiter=',')
print(arr)

[[ 0.580052  0.18673   1.040717  1.134411]
 [ 0.194163 -0.636917 -0.938659  0.124094]
 [-0.12641   0.268607 -0.695724  0.047428]
 [-1.484413  0.004176 -0.744203  0.005487]
 [ 2.302869  0.200131  1.670238 -1.88109 ]
 [-0.19323   1.047233  0.482803  0.960334]]


In [17]:
arr = randn(4,5)
print(arr)
np.savetxt('../resource/savetxt.txt', arr, delimiter='|')

[[ 0.99272058 -1.29667733  1.28687094 -1.68718185 -0.23013874]
 [-0.67044917  1.83304107 -1.5378137   0.31869594 -1.46358893]
 [-0.08360717  0.53059242  0.48221899  0.64943573  0.35902812]
 [ 0.05411431 -1.27427675  0.27376551 -0.3044794   0.40771155]]


In [40]:
arr = np.genfromtxt('../resource/genfromtxt.txt', 
                    delimiter=',')
print(arr)

[[ 1.  2. nan]
 [nan  5.  6.]
 [ 7. nan  9.]]


In [39]:
arr = np.genfromtxt('../resource/genfromtxt.txt', 
                    delimiter=',',
                    names="a,b,c",
                    missing_values={'a':'','b':'','c':''}, # 键是列名
                    filling_values={'a':-1,'b':-2,'c':-3})
print(arr)

[( 1.,  2., -3.) (-1.,  5.,  6.) ( 7., -2.,  9.)]


# 线性代数

In [41]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
print(x.dot(y))
print(np.dot(x,y))

[[ 28  64]
 [ 67 181]]
[[ 28  64]
 [ 67 181]]


In [42]:
print(np.dot(x, np.ones(3)))

[ 6. 15.]


In [45]:
x = np.array([[1,2],[3,4]])
mat = x.T.dot(x)
print(mat)
print(inv(mat))

[[10 14]
 [14 20]]
[[ 5.  -3.5]
 [-3.5  2.5]]


In [46]:
print(mat.dot(inv(mat)))

[[ 1.00000000e+00 -2.66453526e-15]
 [ 7.10542736e-15  1.00000000e+00]]


In [48]:
q, r = qr(mat)
print(q)
print(r)

[[-0.58123819 -0.81373347]
 [-0.81373347  0.58123819]]
[[-17.20465053 -24.41200414]
 [  0.           0.23249528]]


In [49]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
r = np.linalg.solve(a, b)
print(r)

[-1.  1.]


## 随机数生成

In [50]:
# 标准正态分布
sample = np.random.normal(size=(4,4))
print(sample)

[[ 0.21452509  0.86054569  1.04320982 -3.25091413]
 [-0.63439609 -0.74416178  1.0333856   0.02408537]
 [ 0.32384691  1.50815315 -0.06029726  0.89714069]
 [-2.06298773 -0.26640992 -0.93032027 -0.48463629]]


In [52]:
print(np.random.rand(4,4))
print(np.random.randint(5, size=(4,4)))

[[0.89310024 0.18542612 0.43966607 0.08979698]
 [0.51661318 0.58345682 0.36778554 0.78454922]
 [0.33166053 0.95728574 0.50415564 0.20831039]
 [0.00374553 0.42955235 0.32525685 0.36086962]]
[[4 3 2 3]
 [0 2 3 4]
 [4 4 3 2]
 [0 0 0 0]]


## 范例：随机漫步

In [55]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws>0,1,-1)
walk = steps.cumsum()
print((np.abs(walk)>=10).argmax())

63


## 一次模拟多个随机漫步

In [56]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps = np.where(draws>0,1,-1)
walks = steps.cumsum(1)
hits30 = (np.abs(walks)>=30).any(1)
print(hits30)
print(hits30.sum())

[ True False  True ...  True False  True]
3384


In [57]:
crossing_times = (np.abs(walks[hits30])>=30).argmax(1)
print(crossing_times.mean())

503.1625295508274


In [59]:
steps = np.random.normal(loc=0, scale=0.25, size=(nwalks, nsteps))
print(steps)

[[-0.19146873  0.22888976 -0.30905772 ... -0.30283906  0.18404091
  -0.02892877]
 [-0.14631012 -0.15531822 -0.13453228 ...  0.00255435  0.00159295
   0.04394064]
 [-0.09431699  0.12301313  0.05182038 ...  0.05831877  0.08544023
   0.4547216 ]
 ...
 [ 0.42803162  0.1213048   0.14052429 ...  0.20815523 -0.05878678
   0.47321649]
 [ 0.08694055 -0.1081495  -0.20544704 ...  0.38203625  0.24240653
   0.60877502]
 [ 0.19289014  0.07196167 -0.36247542 ...  0.16513907  0.15610533
   0.30490698]]
