In [1]:
import numpy as np
from numpy.random import randn

## 创建ndarray

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

In [6]:
print(arr2.ndim)
print(arr2.shape)

print(arr1.dtype)
print(arr2.dtype)

2
(2, 4)
float64
int32


In [7]:
print(np.zeros(10))

print(np.zeros((3,6)))

print(np.zeros_like(np.zeros((3,6))))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
# 返回的是未初始化的垃圾值
print(np.empty(5))
print(np.empty((2,3)))
print(np.empty((2,3,2))) 


[6.  7.5 8.  0.  1. ]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[1.21476269e-311 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.69119330e-306 1.46301830e+185]]

 [[1.21046140e+161 2.34443391e-056]
  [4.17841785e-062 1.21544342e-046]
  [4.08748830e-033 4.35305725e-061]]]


In [12]:
print(np.arange(5))

[0 1 2 3 4]


In [14]:
print(np.ones((2,3)))
print(np.ones_like(np.ones((2,3))))

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
print(np.eye(3))
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## ndarray数据类型

In [ ]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

In [18]:
arr = np.array([1,2,3,4,5], dtype=np.int32)
floar_arr = arr.astype(np.float64)
print(floar_arr.dtype)

float64


In [22]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr.dtype)
# 被截取
print(arr.astype(np.int32))
print(arr.astype(np.int64))

float64
[ 3 -1 -2  0 12 10]
[ 3 -1 -2  0 12 10]


In [24]:
arr = np.array(['1.25','-9.6','43'],dtype=np.string_)
print(arr.astype(np.float64))
# python类型自动映射到等价的dtype
print(arr.astype(float))

[ 1.25 -9.6  43.  ]
[ 1.25 -9.6  43.  ]


In [26]:
arr = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50], dtype=np.float64)

arr.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
empty_arr = np.empty(4, dtype='u4')
print(empty_arr)

str_arr = np.array(['aa','bb'], dtype='S')
print(str_arr)

[3358653761 3232564447 2552072680  153486976]
[b'aa' b'bb']


## 数组和标量之间的运算

In [32]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr)
# 元素级：对应元素运算
print(arr * arr)
print(arr - arr)
# 数组和标量的运算也会传播到数组的各个元素
print(1 / arr)
print(arr ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## 基本的索引和切片

In [33]:
# 索引从0开始
arr = np.arange(10)
print(arr[5])
print(arr[5:8])

5
[5 6 7]


In [36]:
# 标量值赋给一个切片，值会自动传播
# 对切片的修改，会直接反应到源数组上
arr[5:8] = 12
print(arr)

arr[5:8] = [100,200,300]
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]
[  0   1   2   3   4 100 200 300   8   9]


In [38]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr)
arr_slice[:]= 64
print(arr)

[  100 12345   300]
[    0     1     2     3     4   100 12345   300     8     9]
[ 0  1  2  3  4 64 64 64  8  9]


In [39]:
# 二维数组
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2]) 
print(arr2d[0][2])  
print(arr2d[0,2]) # 等价上条语句

[7 8 9]
3
3


In [41]:
# 三维数组 2*2*3  [[ [],[],[] ], [ [],[],[] ]]
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr3d[0]) # 二维的ndarray
print(arr3d[0,1]) # 一维的ndarray
print(arr3d[0,1, 1]) # 元素值

# 进行几次切片获得单个元素，就是几维数组

[[1 2 3]
 [4 5 6]]
[4 5 6]
5


In [42]:
old_values = arr3d[0].copy()
print(old_values)
arr3d[0] = 42
print(arr3d)
arr3d = old_values
print(arr3d)

[[1 2 3]
 [4 5 6]]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]


In [43]:
print(arr[1:6])
print(arr2d[:2])
print(arr2d[:2,1:]) # 先x 再y

[ 1  2  3  4 64]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


arr2d[:2,1:]

      1:
      ^
    1 |2 3
    4 |5 6
    --|-----> :2
    7 |8 9

In [44]:
print(arr2d[1,:2])
print(arr2d[2,:1])
print(arr2d[:,:1])

[4 5]
[7]
[[1]
 [4]
 [7]]


In [45]:
# 切片表达式的复制操作
print(arr2d)
arr2d[:2,1:] = 0
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]


## 布尔型索引

In [2]:
names = np.array(['Bob','Joe','Will','Bob','Joe','Will','Joe'])
data = randn(7,4)

print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Joe' 'Will' 'Joe']
[[ 0.56937767  0.53038681 -1.45732939  3.5369157 ]
 [-0.48841991  0.40136465  0.7617514  -0.48316186]
 [ 0.98100129 -1.0747141   0.56805005  0.85687133]
 [-0.93795395 -0.69272005 -1.13345997 -0.93248051]
 [-0.34360924  0.74863721  0.37915001 -0.97702183]
 [ 0.69137333 -1.68646787  0.98095027 -0.15901111]
 [-1.05992549  1.20416534  0.42923931 -0.63708581]]


In [4]:
# 数组比较运算
print(names == 'Bob')
# 布尔型数组用于数组索引
# 布尔数组对应到数据数组中，如果对应是true，就取它，如果对应是false，就不取
print(data[names == 'Bob']) # 选出第一行和第四行

[ True False False  True False False False]
[[ 0.56937767  0.53038681 -1.45732939  3.5369157 ]
 [-0.93795395 -0.69272005 -1.13345997 -0.93248051]]


In [6]:
# 布尔型数组用于切片
print(data[names == 'Bob', 2:])

print(data[names == 'Bob', 3])

[[-1.45732939  3.5369157 ]
 [-1.13345997 -0.93248051]]
[ 3.5369157  -0.93248051]


In [9]:
# 取否
print(names != 'Bob')
print(~(names == 'Bob'))
print(data[~(names == 'Bob')])

[False  True  True False  True  True  True]
[False  True  True False  True  True  True]
[[-0.48841991  0.40136465  0.7617514  -0.48316186]
 [ 0.98100129 -1.0747141   0.56805005  0.85687133]
 [-0.34360924  0.74863721  0.37915001 -0.97702183]
 [ 0.69137333 -1.68646787  0.98095027 -0.15901111]
 [-1.05992549  1.20416534  0.42923931 -0.63708581]]


In [11]:
# 布尔条件 $ | !
mask = (names == 'Bob') | (names == 'Will')
print(mask)
print(data[mask])

[ True False  True  True False  True False]
[[ 0.56937767  0.53038681 -1.45732939  3.5369157 ]
 [ 0.98100129 -1.0747141   0.56805005  0.85687133]
 [-0.93795395 -0.69272005 -1.13345997 -0.93248051]
 [ 0.69137333 -1.68646787  0.98095027 -0.15901111]]


In [13]:
# 通过布尔数组选取的数据，是源数据的副本
print(data)
print(data[mask][0,0])

data[mask][0,0] = 11
print(data)

[[ 0.56937767  0.53038681 -1.45732939  3.5369157 ]
 [-0.48841991  0.40136465  0.7617514  -0.48316186]
 [ 0.98100129 -1.0747141   0.56805005  0.85687133]
 [-0.93795395 -0.69272005 -1.13345997 -0.93248051]
 [-0.34360924  0.74863721  0.37915001 -0.97702183]
 [ 0.69137333 -1.68646787  0.98095027 -0.15901111]
 [-1.05992549  1.20416534  0.42923931 -0.63708581]]
0.5693776658683052
[[ 0.56937767  0.53038681 -1.45732939  3.5369157 ]
 [-0.48841991  0.40136465  0.7617514  -0.48316186]
 [ 0.98100129 -1.0747141   0.56805005  0.85687133]
 [-0.93795395 -0.69272005 -1.13345997 -0.93248051]
 [-0.34360924  0.74863721  0.37915001 -0.97702183]
 [ 0.69137333 -1.68646787  0.98095027 -0.15901111]
 [-1.05992549  1.20416534  0.42923931 -0.63708581]]


In [15]:
# 通过布尔数组设置值

# 将data中的负数，设为0
print(data<0)
data[data<0] = 0
print(data)

[[False False  True False]
 [ True False False  True]
 [False  True False False]
 [ True  True  True  True]
 [ True False False  True]
 [False  True False  True]
 [ True False False  True]]
[[0.56937767 0.53038681 0.         3.5369157 ]
 [0.         0.40136465 0.7617514  0.        ]
 [0.98100129 0.         0.56805005 0.85687133]
 [0.         0.         0.         0.        ]
 [0.         0.74863721 0.37915001 0.        ]
 [0.69137333 0.         0.98095027 0.        ]
 [0.         1.20416534 0.42923931 0.        ]]


In [16]:
# 通过布尔数组设置整行整列的值
data[names!='Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.         0.40136465 0.7617514  0.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.         0.74863721 0.37915001 0.        ]
 [7.         7.         7.         7.        ]
 [0.         1.20416534 0.42923931 0.        ]]


## 花式索引

使用整数数组索引，返回的是新数组

In [17]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [21]:
# 传入用于指定顺序的整数列表或ndarray
print(arr[[4,3,0,6]])
# 从末尾-1开始取
print(arr[[-3,-5,-7]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [22]:
arr = np.arange(32).reshape((8,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [23]:
# 第一个数组是取第几行，第二个数组是取对应行的第几个元素
print(arr[[1,5,7,2],[0,3,1,2]])


[ 4 23 29 10]


In [24]:
# 取矩形区域

# 先选取1 5 7 2行，得到一个数组，
# 再数组每行的所有元素，再按照0,3,1,2顺序取每行的元素 
# 【取特定行，对每行元素重新排序】
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [25]:
# 将两个以一维整数数组转换为一个用于选取矩形区域的索引器
"""
Using `ix_` one can quickly construct index arrays that will index
the cross product. ``a[np.ix_([1,3],[2,5])]`` returns the array
``[[a[1,2] a[1,5]], [a[3,2] a[3,5]]]``.
"""
print(np.ix_([1,5,7,2],[0,3,1,2]))
print(arr[np.ix_([1,5,7,2],[0,3,1,2])])

(array([[1],
       [5],
       [7],
       [2]]), array([[0, 3, 1, 2]]))


## 数组转置和轴对换

In [9]:
arr = np.arange(15).reshape((3,5))
print(arr)

arrt = arr.T
print(arrt)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [10]:
# 二维坐标轴
print(arr.transpose((0,1)))
print(arr.transpose((1,0)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [4]:
# 会修改到源数据
arrt[0,1] = 999
print(arrt)
print(arr)

[[  0 999  10]
 [  1   6  11]
 [  2   7  12]
 [  3   8  13]
 [  4   9  14]]
[[  0   1   2   3   4]
 [999   6   7   8   9]
 [ 10  11  12  13  14]]


In [5]:
# 计算内积
arr = np.random.randn(6,3)
print(np.dot(arr.T,arr))

[[ 6.70002934 -0.35599228  2.7046997 ]
 [-0.35599228  7.02082114 -4.16147673]
 [ 2.7046997  -4.16147673 10.81892122]]


In [8]:
# 三维坐标轴
# 将数据放入坐标轴中，更改坐标轴，再依次取出数据
# 0，0，0 -> 0
# 0，1，0 -> 4
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [13]:
arr = np.arange(16).reshape((2, 2, 4))
# 转换y\z轴；x轴不变，所以还是[[],[]]
print(arr.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
